### ISSUE TITLE
Implement agreed date and time representation

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#1325]
**Description** can be found [here](https://github.com/Energinet-DataHub/opengeh-wholesale/issues/677). 

**Acceptance criteria:** 
- [ ] Solution **d)** from [ADR 106](https://energinet.atlassian.net/wiki/spaces/D3/pages/303366148/ADR+106+-+Date+and+Time+Representation) has been implemented. 

**Tech notes:**
- Datepicker is currently implemented in `charges`, `message-archive` and `wholesale`. 
- We do a POC with GraphQL with a custom `date/time` type in the BFF layer, if not possible we need to handle it in the frontend directly where we need to refine a solution in the guild. 

**Tasks:**
- [ ] Make a POC with GraphQL and a custom `date/time` type. @mimse 
- [ ] Present the POC in the guild and agree whats next.

**Comment by BjarkeMeier** [comment]
@frontend-specialisten , @PerLysemose does this story cover the implications in all affected domains? If so it'd probably be a good idea to be more specific about that in the AC. Otherwise, we must ensure that the remaining stories are created too.
