### ISSUE TITLE
[Enabler] Add Nav + Nav items (links/buttons) for the sidebar

### ISSUE THREAD

**Issue by frontend-specialisten** [Energinet-DataHub/greenforce-frontend#142]
**Description**
Add sidebar navigation to Design System.

![image.png](https://images.zenhubusercontent.com/612cb8944df0eb85278b93db/3639d2d8-514e-47bd-b75a-78f1fd3266d5)

[Figma](https://www.figma.com/file/fwEDQkgEcpwfUojXl0EIC5/Watt-Design-System?node-id=1944%3A2381)

**AC**
- [x] Sidebar navigation is added to Design System
- [x] Add link to metering point page to sidebar navigation of DH app
- [x] Showcase and document in storybook

**Note**: Dropdown support is not part of the initial version
