### ISSUE TITLE
Migrate remaining endpoints to GraphQL

### ISSUE THREAD

**Issue by ManBearTM** [Energinet-DataHub/greenforce-frontend#1626]
### Tasks
- [x] CreateBatch mutation
- [x] Actors query
- [x] GridAreas query
- [x] Use CreateBatch mutation in start batch
- [x] Use Actors query in settlement reports
- [x] Use GridAreas query in settlement reports
- [x] Remove component store
