### ISSUE TITLE
[Cancelled] View Metering Point Process Steps 

### ISSUE THREAD

**Issue by stephaniegitha** [Energinet-DataHub/greenforce-frontend#173]
As Niels, grid company user, I want to get an overview of my metering point processes and its statuses so that I can verify the latest updates on my metering point with my own system

### Acceptance Criteria 
- [ ] Expand row and display "step rows" (step name, sender, receiver, creation date, cut-off-date, step status)
- [ ] Sort by creation date as default (oldest first)
- [ ] Show "step row" status with colors:
- Green = completed steps
- Red = rejected steps 
- Grey = pending steps

- [ ] Show only "DataHub" as name if "SenderEnergyParty" or "RecipientEnergyParty" is Energinet DataHub A/S (DHB) (GLN number: 5790001330552)
- [ ] Show both name and GLN number in parentheses if "SenderEnergyParty" or "RecipientEnergyParty" is other than  Energinet DataHub A/S (DHB) (GLN number: 5790001330552) 
- [ ] Show rejection message
- [ ] Open XML message **in new tab**
- [ ] Align with UX

➡️ &nbsp;[LINK TO PROTOTYPE](https://www.figma.com/proto/5lCd6Wq5bcDkOXIMgyLST6/DataHub-3.0?page-id=562%3A2395&node-id=665%3A8433&viewport=351%2C48%2C0.44&scaling=contain&starting-point-node-id=665%3A8433&show-proto-sidebar=1)

### Missing 
- [ ] Alignment with Batman
- [ ] Translations
- [ ] Align how dates should be formatted with business (reach out to Mogens)
- [ ] (UX) Add view in Figma for multiple rejection messages (i.e. bullet list, or something else?)

### Processes in scope

- BRS-004 - Opret målepunkt
- BRS-006 - Vedligehold stamdata på målepunkt 
- BRS-008 - Tilslut målepunkt 

https://energinet.dk/El/DataHub/Dokumentation-og-regler

### Stakeholders

- Christian Meyer (PO, Batman)
- Dorthe og Maria (Support)

**Comment by mknic** [comment]
@dzhavat @frontend-specialisten should we close this? I presume it has been implemented?

**Comment by dzhavat** [comment]
@mknic By looking at the description and ACs, it doesn't look like everything is implemented. Similarly to a [comment](https://github.com/Energinet-DataHub/greenforce-frontend/issues/120#issuecomment-1121041074) in #120 some things are implemented partially.

Maybe the issue can still be closed and any further improvements/changes can be under a new issue.
