### ISSUE TITLE
Remove material legacy components

### ISSUE THREAD

**Issue by mimse** [Energinet-DataHub/greenforce-frontend#1930]
We need to remove material legacy components. So we can upgrade to angular 17 when it lands.

Components to be converted

- [x] - legacy-card (EO) PR #2051
- [x] - legacy-paginator (EO) @frontend-specialisten
- [x] - legacy-table (EO) @frontend-specialisten 
- [x] - legacy-slide-toggle (EO) PR #2053
- [x] - legacy-radio (EO) PR #2054
- [x] - legacy-dialog
- [x] - legacy-snack-bar
- [x] - legacy-select/testing (mvt)
- [x] - legacy-select (mvt)
- [x] - legacy-paginator (mvt)
- [x] - legacy-table
- [x] - legacy-tooltip
- [x] - legacy-menu
- [x] - legacy-button (EO) [PR #2010](https://github.com/Energinet-DataHub/greenforce-frontend/pull/2010)
- [x] - legacy-checkbox
- [x] - legacy-form-field
- [x] - legacy-input
- [x] - legacy-list
- [x] - legacy-progress-spinner
