### ISSUE TITLE
Update to Angular v17

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#2364]
### To-do

- [x] Update Angular Material to v17
- [x] Check components in Storybook
- [x] Fix warnings in console
- [x] Update NgRx to v17
- [x] Migrate Angular Material legacy components
- [x] Replace `@` character with `&#64;` in places where `@` is meant to be displayed
- [x] Fix lint error in `libs/dh/message-archive/domain/src/lib/documentTypes.ts`
- [x] Remove/Adjust styling applied to `-legacy` classes
