### ISSUE TITLE
Spring cleaning på beregninger

### ISSUE THREAD

**Issue by PernilleChristiansen** [Energinet-DataHub/greenforce-frontend#2614]
## Synopsis
As a ...
I want ...
So that ... 

https://www.figma.com/file/RtPNDzY64YytPvmBDI73Gl/UX-Review-februar-2024?type=design&node-id=49%3A250&mode=design&t=dPOkqdrE1uF7reWY-1

## Acceptance Criteria
- [X] Spacing mellem chips
- [x] Common grid area display name
 
#### Required documentation
(Check only those that are relevant)
   - [ ] Business (Confluence)
   - [ ] C4 (dsl)
   - [ ] Technical (Github)

## Testing

<-- How and if this story should be tested. E.g. should it be tested on multiple environments, does it require verification from a business consultant, data validation team, other DH3 teams etc. -->

#### Required tests
(Check only those that are relevant)
 - [ ] Unit
 - [ ] Feature
 - [ ] Calculator job
 - [ ] Subsystem
 - [ ] Other automation (elaborate below)
 - [ ] Manual test (elaborate below)

## Tasks

- [ ] ...

## Tech Notes
...

## Developer Test Notes
...

<-- Please note here what has already been tested before moving to "Test" column -->

## DoR
Definition of Ready - before moving story to **Backlog**, story should have:
 - Synopsis
 - Acceptance Criteria
 - Test section 
 - Estimate

## DoD
Definition of Done - before moving story to **Test**, story should have:
 - Required automation written, passing CI
 - Required Documentation written, reviewed
 - Developer test notes
