### ISSUE TITLE
[Enabler] Expand design system to support business overview screens

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/greenforce-frontend#277]
**Description**

Extend the Design System to contain new components and modifications to existing components to be ready to support business overview screens, hereby: processes and status for metering points and charges.

**AC**
- [x] Add expandable table rows component
- [x] Add alert message box (see process step for message denied)
- [x] Add link icon
- [x] Support state colors of icon component
- [x] Add checkbox component
