### ISSUE TITLE
Design System improvements

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/greenforce-frontend#289]
**Description**
We need to add a couple of missing components already planned and we also have some improvements to already existing components.

**AC**
- [ ] Reset margins
- [ ] Add skeleton loader (discuss with @jonaseilsoe )
- [ ] Add breadcrumb component
- [x] Add nav + nav items component
- [x] Fix spacing issues on button suffix in text field component
- [ ] Align typographies with latest changes from UX
- [ ] Align colors with latest changes from UX
- [ ] Text colors / theming (light and dark)
- [ ] Table with pagination (styling)
- [ ] Sidebar width
- [ ] Spacing around the main content
- [ ] Update topbar height
