### ISSUE TITLE
Logging and user insights

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/greenforce-frontend#291]
**Description**
As a buisness we want to be able to trace any request from its starting point to the end
So that we have a single source of truth where any request can be traced from start to end.

We want to have user insights to ensure we continuously improve our products' user experience.
By tracking user paths when using the system we can proactively improve workflows.

**Benefit Hypothesis**
We want to be in a good position to support our application to be able to know what users are doing and if they are encountering any issues.

**Ideas to what to track**
- [ ] If a user is authenticated or not
- [ ] Routing events
- [ ] unhandled errors
- [ ] Page Views

**AC**
- [ ] Enable user insights analytics
- [ ] Add integration to Application Insights from Angular
- [ ] Add `traceparent` to correlate a request in frontend with BFF and further down the stack

**Notes from Dan **
![image.png](https://images.zenhubusercontent.com/612cbcaa9fd6401e03dda309/16f0569a-5a99-45d1-a271-1c91e9ff3580)
![image.png](https://images.zenhubusercontent.com/612cbcaa9fd6401e03dda309/7189992c-7a53-4cc9-b3a1-f42f45a7f96e)
