### ISSUE TITLE
Create wireframe design

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/greenforce-frontend#320]
**AC**
- [ ] Create wireframe design
- [ ] Get design reviewed by frontend guys
- [ ] Get design reviewed by support
