### ISSUE TITLE
Implement CookieInformation banner

### ISSUE THREAD

**Issue by ManBearTM** [Energinet-DataHub/greenforce-frontend#3562]
## Tasks
- [ ] Display cookie banner upon first visit to site
- [ ] Display renew button in bottom right corner
- [ ] Use english version of cookie banner when changing languages
- [ ] Remove Application Insights cookies when withdrawing consent
- [ ] Add Application Insights cookies when granting consent
