### ISSUE TITLE
[Enabler] Design charge details page

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/greenforce-frontend#391]
**Description**
Design the charge details page to enable the product team to implement the UI part of the flows using the Design System.

1. Charge price details page
1a. master data and price information (historical timeline to see changes to price over time)
1b. Calendar (from-to) on the details view

**Links**
Miro board to show initial thoughts on UX flows based on knowhow from current datahub:
https://miro.com/app/board/o9J_kq0bac0=/

This feature enables the following business feature:
https://app.zenhub.com/workspaces/feature-board-60e2eb437d96850014aa15ab/issues/energinet-datahub/geh-charges/1130

**AC**
- [x] Design master data section and document in Figma
- [ ] Design price history section/page and document in Figma
- [x] Design details current price section and document in Figma
- [x] On the charge details page it should be possible to filter on a from and to date
