### ISSUE TITLE
[Enabler] Feature flagging in Angular

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/greenforce-frontend#393]
**Description**
As a platform team, we want to enable the product teams to toggle UI related features on/off
so that they are able to release UI related features under development and be in control of which features are enabled/disabled

**Links**
https://sreyaj.dev/implementing-feature-flags-in-angular

**Technical Note**
- Thought: Deploy the application and replace the feature flag file instead of having separate deployments per environment. 
- Consider how the feature flags affect our test suite.

**Question**
Should it be possible to toggle the feature flag on/off in the dev environment (u001)?

**AC**
- [x] Sample feature flag service in Angular is developed and documented
- [x] Feature flag service has been tried and verified together with a product team
- [x] Feedback from teams are documented and issues are created to handle need-to-have feedback
- [x] Product teams are notified about the sample feature flag service and know where to find it
- [x] Feature flag is configurable in each environment
- [x] It should be possible to toggle menu items on/off

**Comment by mknic** [comment]
@PerTHenriksen let's catch up on this feature and figure out when/how you want to use version 1 of feature flagging in Angular (frontend) in the wholesale area.
