### ISSUE TITLE
Date-picker

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#410]
**Description**
As a product team I need a datepicker component
So that I am able to select a single date and a date range

**AC**
- [x] It should be possible to select a single date
- [x] It should be possible to select a date range
- [x] It should be compatible with both Danish and English language
