### ISSUE TITLE
[Enabler] Create Modal component

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/greenforce-frontend#587]
**Description**

**AC**
- [x] Should support "small", "medium" and "large" sizes (height and width)
- [x] Should have a backdrop
- [x] Should be configurable so it can't be dismissed
- [x] Should have scrollable content (fixed action buttons at the bottom)
- [x] Should have borders on top and bottom of the content when overflowed (scrollable)
- [x] Should be added to Design System in Figma
- [x] Should be showcased in Storybook

**Tech notes**
- Dialog component in Material https://material.angular.io/components/dialog/overview
- Check focus trap

**Out of scope**
- This component is not a drawer. A drawer component will be build in another feature.
- Mobile view is not supported
