### ISSUE TITLE
User/role authorization

### ISSUE THREAD

**Issue by dzhavat** [Energinet-DataHub/greenforce-frontend#600]
Should be possible to show/hide content depending on a user role.

Authorization determines what resources a user can access.

**AC**
- [ ] Should be able to show/hide content based on user's role in the template
- [ ] Should be able to guard a route based on user's role
- [ ] Should redirect to an error page in case a route guard rejects navigation due to "403 Forbidden" error

**Clarifications**
- How granular are the roles? "Admin" vs "canSee + canEdit"
