### ISSUE TITLE
[Enabler] Create drawer component

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/greenforce-frontend#651]
**Description**
As a product team member, we want a component in the Design System
So that we can build detailed content views

Screenshot from Figma:
![image.png](https://images.zenhubusercontent.com/60daf62b0365bf75ac4f3d5d/5d8d46f1-2a0d-4ce4-a77f-5493540b3859)

**AC**
- [ ] Should support "small", "normal" and "large" sizes (width)
- [ ] Header should be configurable. Example: breadcrumbs
- [ ] Drawer as overlay and should not push content
- [ ] Should not have a backdrop
- [ ] Should have scrollable content (fixed action buttons at the top)
- [ ] Should be added to Design System in Figma
- [ ] Should be showcased in Storybook

**Tech notes**
https://www.figma.com/file/4tVkjKm5fkIj61nx4XD3pA/DataHub-3.0?node-id=3217%3A38669
