### ISSUE TITLE
Feature Flagging

### ISSUE THREAD

**Issue by kariws** [Energinet-DataHub/greenforce-frontend#688]
**Description**
As a business, we want to be able to separate deployment from release and still be able to work in a trunk-based development environment
So that we can continuously deploy and release code to production and have full control over which features are available for the customers.

**AC**
- [x] Implement feature flags in Angular
- [x] Implement feature flags in .NET
- [x] Feature flags are toggled on deployment
- [x] Write documentation on usage feature flags in Angular
- [x] Write documentation on usage feature flags in .NET
