### ISSUE TITLE
UX process documentation for quality assurance

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/greenforce-frontend#982]
**Description**
AS A FEATURE TEAM we want to know the UX process
SO THAT we secure best practices and quality when designing new requirements

AS A FEATURE TEAM I want to know the UX process
SO THAT I can split UI features without breaking the intended design

AS A DESIGN SYSTEM CONTRIBUTOR I need to know the process of coming from design in Figma to add the component to the design system
SO THAT we are able to contribute to the design system

**AC**
- [ ] Verify documentation with frontenders in Batman and Titans to get input
- [ ] Add input as new stories
- [ ] Document in confluence
