### ISSUE TITLE
[Enabler] Redesign Organisations page

### ISSUE THREAD

**Issue by renehossle** [Energinet-DataHub/greenforce-frontend#990]
**Description**
As a Datahub user
I want to be able to create and edit Organisations with the same user experience as the rest of Datahub
So that I don't have to struggle to understand the interface

**Clarification**
- Can we get this prioritised into the roadmap?

**AC**
- [ ] Align user flow to match same patterns as in rest of Datahub
- [ ] Make use of new component logic such as drawer and modal
- [ ] Build prototype based on these requirements with components from WATT
- [ ] Demonstrate flows from start to finish
- [ ] Verify with stakeholders

**Definition of Ready**
- [ ] The issue is correctly estimated
- [ ] The issue is adequately described
- [ ] Possible dependencies are defined and aligned
- [ ] We have the necessary skills to complete this issue
- [ ] The issue can be completed within 1 iteration
- [ ] The issue has acceptance criteria defined
- [ ] The issue has adequate Definition Of Done described

**Definition of Done**
- [ ] Acceptance Criteria have been met
- [ ] The product has been demo’ed for relevant stakeholders
- [ ] Dependencies are handled
- [ ] The work has been documented
- [ ] The issue has been handed over and reviewed
- [ ] The PO has accepted the product
